version: "3.7"

networks:
 logstashinet:
  name: logstashnet
  driver: bridge

services:
  logstash:
    image: logstash_image:latest
    container_name: logstashh
    user: "root"
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./logstash/pipeline/logstash-tj.config:/usr/share/logstash/pipeline/logstash-tj.config
      - ./logs:/var/log/logtj
      - ./input:/usr/share/logstash/data/input
      - ./output:/usr/share/logstash/data/output:rw
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml  
    networks:
      - logstashinet
    logging:
      options:
        max-size: "100m"
        max-file: "3"
    command: logstash -f /usr/share/logstash/pipeline/logstash-tj.config
