version: "3.7"
networks:
 elastic:
  name: elastic
  driver: bridge
services:
  elasticsearch:    
    image: elasticsearch:7.17.12
    container_name: ess
    restart: unless-stopped
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    logging:
      options:
        max-size: "100m"
        max-file: "3"
  kibana:
    image: kibana:7.17.12  
    container_name: kibana_lgg
    restart: unless-stopped
    networks:
      - elastic
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    logging:
      options:
        max-size: "100m"
        max-file: "3"
  logstash:
    image: logstash:7.16.1
    container_name: logstashh
    user: "root" 
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./logstash/pipeline/logstash-tj.config:/usr/share/logstash/pipeline/logstash-tj.config
      - ./logs:/var/log/logtj
      - ./input:/usr/share/logstash/data/input
      - ./output:/usr/share/logstash/data/output:rw
    ports:
      - "5005:5005/tcp"
      - "5005:5005/udp"
      - "5044:5044"
      - "9600:9600"
    networks:
      - elastic
    logging:
      options:
        max-size: "100m"
        max-file: "3"
    command: logstash -f /usr/share/logstash/pipeline/logstash-tj.config
